apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextflowsvcacc

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create
  namespace: nextflowdemo
subjects:
  - kind: ServiceAccount
    name: nextflowsvcacc
    namespace: nextflowdemo
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
